################################################################################
# \file bsp.mk
#
# \brief
# Define the KIT_T2G-B-E_LITE target.
#
################################################################################
# \copyright
# Copyright 2021-2022 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
# Use a default CM0+ image (CM0P_SLEEP). This can be swapped for a
# different pre-built image or removed if custom built project.
BSP_COMPONENTS:=CM0P_SLEEP

# Any additional defines to apply when using this board.
BSP_DEFINES:=CY_USING_HAL

# Path to the flash loaders to patch for this board
#CY_QSPI_FLM_DIR=$(MTB_TOOLS__TARGET_DIR)/config/FlashLoaders/

# Path to the patched flash loaders for this board
#CY_QSPI_FLM_DIR_OUTPUT=$(MTB_TOOLS__TARGET_DIR)/config/GeneratedSource/

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYT2BL5CAS
DEVICE:=CYT2BL5CAS
DEVICE_COMPONENTS:=CAT1 CAT1A TVIIBE4M
DEVICE_CYT2BL5CAS_CORES:=CORE_NAME_CM0P_0 CORE_NAME_CM4_0
DEVICE_CYT2BL5CAS_DIE:=TVIIBE4M
DEVICE_CYT2BL5CAS_FEATURES:=CM4_0_FPU_PRESENT
DEVICE_CYT2BL5CAS_FLASH_KB:=4160
DEVICE_CYT2BL5CAS_SRAM_KB:=512
DEVICE_LIST:=CYT2BL5CAS
DEVICE_TOOL_IDS:=bsp-assistant device-configurator dfuh-tool library-manager project-creator smartio-configurator
RECIPE_DIR:=$(SEARCH_recipe-make-cat1a)
